on: push
name: verify
jobs:
  build:
    name: install
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: setup node
      uses: actions/setup-node@v1
      with:
        node-version: 10
    - run: npm install
    - run: npm test
      
