on: push
name: main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: |
          npm ci
          npm run build --if-present
          npm test
        env: 
          NODE_AUTH_TOKEN: ${{secrets.GPR_TOKEN}}
          CI: true
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
          scope: '@cpilsworth'
      - name: setup auth
        run: echo "//registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN}" >> .npmrc
        env: 
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}            
      - run: npm publish
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
  
  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v1
        with:
          node-version: 12       
          registry-url: 'https://npm.pkg.github.com' 
          scope: '@cpilsworth'
      - name: setup auth
        run: echo "//npm.pkg.github.com/:_authToken=${GITHUB_TOKEN}" >> .npmrc
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}          
      - name: npm publish gpr (on tag)
        run: npm publish 
        env:
          NODE_AUTH_TOKEN: ${{secrets.GPR_TOKEN}}
        if: contains(github.ref, 'tags')
